-- E-Vidente 3.0 - Migração Completa para Português (Corrigido)

-- ATENÇÃO: Habilite a extensão pgcrypto se ainda não estiver
create extension if not exists pgcrypto;

-- ==========================================
-- 1. TABELAS DE DOMÍNIO (Migradas)
-- ==========================================

-- 1.1 PERFIS (antigo 'profiles')
create table if not exists perfis (
  id uuid references auth.users(id) on delete cascade primary key,
  nome_completo text,
  avatar_url text,
  email text,
  acesso_bia boolean default false, -- mantendo compatibilidade temporária
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table perfis enable row level security;
create policy "Perfis visíveis pelo próprio usuário" on perfis for select using (auth.uid() = id);
create policy "Usuários podem atualizar próprio perfil" on perfis for update using (auth.uid() = id);

-- Migração de Dados: profiles -> perfis
insert into perfis (id, nome_completo, avatar_url, email, acesso_bia)
select id, full_name, avatar_url, email, acesso_bia from profiles
on conflict (id) do nothing;


-- 1.2 EVIDÊNCIAS (antigo 'evidences')
create table if not exists evidencias (
  id bigint generated by default as identity primary key,
  titulo text not null,
  resumo text,
  acao text,
  tags text[],
  validade_interna text,
  validade_externa text,
  confiabilidade text,
  link text,
  ano int,
  detalhes jsonb,
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table evidencias enable row level security;
create policy "Evidências públicas para leitura" on evidencias for select using (true);

-- Migração de Dados: evidences -> evidencias
-- Adicionado CAST para bigint caso a origem esteja mal tipada
insert into evidencias (id, titulo, resumo, acao, tags, validade_interna, validade_externa, confiabilidade, link, ano, detalhes)
select id::bigint, title, summary, action, tags, validade_interna, validade_externa, confiabilidade, link, year, details
from evidences
on conflict (id) do nothing;


-- 1.3 FAVORITOS (antigo 'favorites')
create table if not exists favoritos (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users(id) on delete cascade not null,
  evidencia_id bigint references evidencias(id) on delete cascade not null,
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(usuario_id, evidencia_id)
);

alter table favoritos enable row level security;
create policy "Usuários podem ver seus favoritos" on favoritos for select using (auth.uid() = usuario_id);
create policy "Usuários podem adicionar favoritos" on favoritos for insert with check (auth.uid() = usuario_id);
create policy "Usuários podem remover favoritos" on favoritos for delete using (auth.uid() = usuario_id);

-- Migração de Dados: favorites -> favoritos
-- FIX: Casting evidence_id to bigint to resolve type mismatch
insert into favoritos (usuario_id, evidencia_id, criado_em)
select user_id, evidence_id::bigint, created_at
from favorites
on conflict (usuario_id, evidencia_id) do nothing;


-- ==========================================
-- 2. NOVAS TABELAS SAAS (E-Vidente 3.0)
-- ==========================================

-- 2.1 PRODUTOS
create table if not exists produtos (
  id uuid default gen_random_uuid() primary key,
  nome text not null,
  slug text not null unique,
  tipo text check (tipo in ('curso', 'ferramenta')) not null,
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table produtos enable row level security;
create policy "Produtos visíveis para todos" on produtos for select using (true);

-- Seed Inicial
insert into produtos (nome, slug, tipo) values ('E-Vidente', 'e-vidente', 'ferramenta') on conflict (slug) do nothing;


-- 2.2 PRODUTOS DO USUÁRIO (Acesso)
create table if not exists produtos_usuario (
  id uuid default gen_random_uuid() primary key,
  usuario_id uuid references auth.users(id) on delete cascade not null,
  produto_id uuid references produtos(id) on delete cascade not null,
  ativo boolean default true not null,
  concedido_em timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(usuario_id, produto_id)
);

alter table produtos_usuario enable row level security;
create policy "Usuários veem seus produtos" on produtos_usuario for select using (auth.uid() = usuario_id);

-- Migração: Quem já tinha acesso_bia ganha o produto E-Vidente
insert into produtos_usuario (usuario_id, produto_id, ativo)
select p.id, (select id from produtos where slug = 'e-vidente'), true
from perfis p
where p.acesso_bia = true
on conflict (usuario_id, produto_id) do nothing;


-- 2.3 PLANOS SALVOS
create table if not exists planos_salvos (
  id uuid default gen_random_uuid() primary key,
  usuario_id uuid references auth.users(id) on delete cascade not null,
  titulo text not null,
  conteudo_html text not null,
  persona text,
  estilo text,
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table planos_salvos enable row level security;
create policy "CRUD Planos Próprios" on planos_salvos using (auth.uid() = usuario_id);


-- 2.4 LOGS DE USO
create table if not exists logs_uso (
  id uuid default gen_random_uuid() primary key,
  usuario_id uuid references auth.users(id) on delete set null,
  acao text not null, 
  modelo text not null, 
  custo_creditos int default 0,
  criado_em timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table logs_uso enable row level security;
create policy "Ver logs próprios" on logs_uso for select using (auth.uid() = usuario_id);
create policy "Inserir logs" on logs_uso for insert with check (auth.uid() = usuario_id);
